tritunggal/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  resources :about_us, :only => [:index]
  resources :certificates, :only => [:index]
  resources :contact_us, :only => [:index, :create]
  get "/news" => "news#index", :as => "news"
  get "/news/:permalink" => "news#show", :as => "news_detail"
  get "products/search" => "products#search", :as => "product_search"
  get "products/:cat_permalink" => "products#index", :as => "products"
  get "products/:cat_permalink/:prod_permalink" => "products#show", :as => "product_detail"

  get "admin" => "admin/dashboard#index", :as => "admin"
  namespace :admin do
    resources :banners
    resources :categories
    resources :certificate_categories
    resources :certificates
    resources :clients
    resources :news
    get "product/products_by_category/:cat_permalink" => "products#products_by_category",
        :as => "products_by_category"
    get "contact_us_list" => "contact_us#index", :as => "contact_us_list"
    get "contact_us/:id" => "contact_us#show", :as => "contact_us"
    delete "contact_us/:id" => "contact_us#destroy", :as => "delete_contact_us"
    resources :products do
      member do
        resources :product_images, :param => :product_image_id
        resources :product_specifications, :param => :product_specification_id
      end
    end
    resources :system_settings, :only => [:edit, :update]
  end

  root 'home#index'

end

tritunggal/app/models/certificate_category.rb
class CertificateCategory < ActiveRecord::Base
  has_many :certificates

  validates :name, :presence => true
end

tritunggal/app/controllers/admin/certificate_categories_controller.rb
class Admin::CertificateCategoriesController < Admin::ApplicationController
  before_filter :find_certificate, :only => [:edit, :update, :destroy, :delete]

  def index
    @certificate_categories = CertificateCategory.
                                order("#{sort_column} #{sort_direction}").page(params[:page]).per(20)
    @no = paging(20)
  end

  def new
    @certificate_category = CertificateCategory.new
  end

  def create
    @certificate_category = CertificateCategory.new(certificate_params)
    if @certificate_category.save
      flash[:notice] = 'CertificateCategory was successfully create.'
      redirect_to admin_certificate_categories_path
    else
      flash[:error] = "CertificateCategory failed to create"
      render :action => :new
    end
  end

  def edit
  end

  def update
    if @certificate_category.update_attributes(certificate_params)
      flash[:notice] = 'CertificateCategory was successfully updated.'
      redirect_to admin_certificate_categories_path
    else
      flash[:error] = "CertificateCategory failed to update"
      render :action => :edit
    end
  end

  def destroy
    flash[:notice] =  @certificate_category.destroy ? 'CertificateCategory was successfully deleted.' :
                                           'CertificateCategory was falied to delete.'
    redirect_to admin_certificate_categories_path
  end

  private

    def certificate_params
      params.require(:certificate_category).permit(:name)
    end

    def find_certificate
      @certificate_category = CertificateCategory.find_by_id(params[:id])
      if @certificate_category.nil?
        flash[:notice] = "Cannot find the CertificateCategory with id '#{params[:id]}'"
        redirect_to admin_certificate_categories_path
      end
    end

    def sort_column
      params[:sort] || "created_at"
    end

    def sort_direction
      params[:direction] || "desc"
    end
end

tritunggal/app/views/admin/certificate_categories/_form.html.erb
<% if @certificate_category.errors.any? %>
  <div class="alert alert-danger alert-dismissable" group="alert">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
    </button>
    <h4><%= pluralize(@certificate_category.errors.count, "error") %> prohibited this group from being saved:</h4>
    <ul>
    <% @certificate_category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= f.label :name, "Name *", :class => "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :name, :class => "form-control" %>
  </div>
</div>

tritunggal/app/views/admin/certificate_categories/edit.html.erb
<div class="page-header">
  <div class="container">
    <div class="col-xs-12 col-sm-4 name no-padding-lr">Edit Certificate Category</div>
    <div class="col-xs-12 col-sm-8 breadcrumb">
      <ol class="breadcrumb">
        <li><%= link_to "Admin", admin_path %></li>
        <li><%= link_to "Certificate Categories", admin_certificate_categories_path %></li>
        <li class="active">Edit Certificate Category</li>
      </ol>
    </div>
  </div>
</div>

<div class="container">
  <%= render :partial => "shared/flash" %>
  <%= form_for([:admin, @certificate_category],
              :html => {:multipart => true, :class => "form-horizontal"}) do |f| %>
    <%= render :partial => 'form', :locals => { :f => f} %>
    <div class="form-group">
      <div class="col-sm-2">&nbsp;</div>
      <div class="col-sm-10">
        <%= f.submit :class => "btn btn-success" %>
        <%= link_to 'Back', admin_certificate_categories_path, :class => "btn btn-info" %>
      </div>
    </div>
  <% end %>
</div>

tritunggal/app/views/admin/certificate_categories/index.html.erb
<div class="page-header">
  <div class="container">
    <div class="col-xs-12 col-sm-4 name no-padding-lr">Certificate Categories</div>
    <div class="col-xs-12 col-sm-8 breadcrumb">
      <ol class="breadcrumb">
        <li><%= link_to "Admin", admin_path %></li>
        <li class="active">Certificate Categories</li>
      </ol>
    </div>
  </div>
</div>

<div class="container">
  <%= render :partial => "shared/flash" %>
  <p><%= link_to "Add new Certificate Category", new_admin_certificate_category_path %></p>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th class="green-link"><%= sortable("name", "Name") %></th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @certificate_categories.each_with_index do |certificate_category, x| %>
        <tr>
          <th><%= @no+x+1 %></th>
          <td><%= certificate_category.name.titleize %></td>
          <td>
            <%= link_to "Edit", edit_admin_certificate_category_path(certificate_category.id),
                                :class => "btn btn-success" %>
            <%= link_to "Delete", admin_certificate_category_path(certificate_category.id ),
                                  :method => :delete,
                                  :data => {:confirm => "Are you sure?"}, :class => "btn btn-warning" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="col-xs-12 no_padding_lr pagination"><%= paginate @certificate_categories %></div>
</div>

tritunggal/app/views/admin/certificate_categories/new.html.erb
<div class="page-header">
  <div class="container">
    <div class="col-xs-12 col-sm-4 name no-padding-lr">New Certificate Category</div>
    <div class="col-xs-12 col-sm-8 breadcrumb">
      <ol class="breadcrumb">
        <li><%= link_to "Admin", admin_path %></li>
        <li><%= link_to "Certificate Categories", admin_certificate_categories_path %></li>
        <li class="active">New Certificate Category</li>
      </ol>
    </div>
  </div>
</div>

<div class="container">
  <%= render :partial => "shared/flash" %>
  <%= form_for([:admin, @certificate_category],
              :html => { :multipart => true,  :class => "form-horizontal"}) do |f| %>
    <%= render :partial => 'form', :locals => { :f => f} %>
    <div class="form-group">
      <div class="col-sm-2">&nbsp;</div>
      <div class="col-sm-10">
        <%= f.submit :class => "btn btn-success" %>
        <%= link_to 'Back', admin_certificate_categories_path, :class => "btn btn-info" %>
      </div>
    </div>
  <% end %>
</div>