tritunggal/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  resources :about_us, :only => [:index]
  resources :certificates, :only => [:index]
  resources :contact_us, :only => [:index, :create]
  get "/news" => "news#index", :as => "news"
  get "/news/:permalink" => "news#show", :as => "news_detail"
  get "products/search" => "products#search", :as => "product_search"
  get "products/:cat_permalink" => "products#index", :as => "products"
  get "products/:cat_permalink/:prod_permalink" => "products#show", :as => "product_detail"

  get "admin" => "admin/dashboard#index", :as => "admin"
  namespace :admin do
    resources :banners
    resources :categories
    resources :certificate_categories
    resources :certificates
    resources :clients
    resources :news
    get "product/products_by_category/:cat_permalink" => "products#products_by_category",
        :as => "products_by_category"
    get "contact_us_list" => "contact_us#index", :as => "contact_us_list"
    get "contact_us/:id" => "contact_us#show", :as => "contact_us"
    delete "contact_us/:id" => "contact_us#destroy", :as => "delete_contact_us"
    resources :products do
      member do
        resources :product_images, :param => :product_image_id
        resources :product_specifications, :param => :product_specification_id
      end
    end
    resources :system_settings, :only => [:edit, :update]
  end

  root 'home#index'

end

tritunggal/app/models/client.rb
class Client < ActiveRecord::Base
  mount_uploader :logo, ClientLogoUploader

  validates :name, :presence => true
end

tritunggal/app/controllers/admin/clients_controller.rb
class Admin::ClientsController < Admin::ApplicationController
  before_filter :find_client, :only => [:edit, :update, :destroy, :delete]

  def index
    @clients = Client.order("#{sort_column} #{sort_direction}").page(params[:page]).per(20)
    @no = paging(20)
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      flash[:notice] = 'Client was successfully create.'
      redirect_to admin_clients_path
    else
      flash[:error] = "Client failed to create"
      render :action => :new
    end
  end

  def edit
  end

  def update
    if @client.update_attributes(client_params)
      flash[:notice] = 'Client was successfully updated.'
      redirect_to admin_clients_path
    else
      flash[:error] = "Client failed to update"
      render :action => :edit
    end
  end

  def destroy
    flash[:notice] =  @client.destroy ? 'Client was successfully deleted.' :
                                           'Client was falied to delete.'
    redirect_to admin_clients_path
  end

  private

    def client_params
      params.require(:client).permit(:name, :logo)
    end

    def find_client
      @client = Client.find_by_id(params[:id])
      if @client.nil?
        flash[:notice] = "Cannot find the Client with id '#{params[:id]}'"
        redirect_to admin_clients_path
      end
    end

    def sort_column
      params[:sort] || "created_at"
    end

    def sort_direction
      params[:direction] || "desc"
    end
end

tritunggal/app/views/admin/clients/_form.html.erb
<% if @client.errors.any? %>
  <div class="alert alert-danger alert-dismissable" group="alert">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
    </button>
    <h4><%= pluralize(@client.errors.count, "error") %> prohibited this group from being saved:</h4>
    <ul>
    <% @client.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= f.label :name, "Name *", :class => "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :name, :class => "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= f.label :logo, "Logo", :class => "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.file_field :logo, :class => "form-control" %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-2">&nbsp;</div>
  <div class="col-sm-10">
    Please upload image with size 600x600 pixel (height x width)
  </div>
</div>

tritunggal/app/views/admin/clients/edit.html.erb
<div class="page-header">
  <div class="container">
    <div class="col-xs-12 col-sm-4 name no-padding-lr">Edit Client</div>
    <div class="col-xs-12 col-sm-8 breadcrumb">
      <ol class="breadcrumb">
        <li><%= link_to "Admin", admin_path %></li>
        <li><%= link_to "Clients", admin_clients_path %></li>
        <li class="active">Edit Client</li>
      </ol>
    </div>
  </div>
</div>

<div class="container">
  <%= render :partial => "shared/flash" %>
  <%= form_for([:admin, @client], :html => { :multipart => true, :class => "form-horizontal"}) do |f| %>
    <div class="form-group">
      <div class="col-sm-12">
        <%= image_tag @client.logo.url(:thumb) %>
      </div>
    </div>
    <%= render :partial => 'form', :locals => { :f => f} %>
    <div class="form-group">
      <div class="col-sm-2">&nbsp;</div>
      <div class="col-sm-10">
        <%= f.submit :class => "btn btn-success" %>
        <%= link_to 'Back', admin_clients_path, :class => "btn btn-info" %>
      </div>
    </div>
  <% end %>
</div>

tritunggal/app/views/admin/clients/index.html.erb
<div class="page-header">
  <div class="container">
    <div class="col-xs-12 col-sm-4 name no-padding-lr">Clients</div>
    <div class="col-xs-12 col-sm-8 breadcrumb">
      <ol class="breadcrumb">
        <li><%= link_to "Admin", admin_path %></li>
        <li class="active">Clients</li>
      </ol>
    </div>
  </div>
</div>

<div class="container">
  <%= render :partial => "shared/flash" %>
  <p><%= link_to "Add new client", new_admin_client_path %></p>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Logo</th>
        <th>Name</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @clients.each_with_index do |client, x| %>
        <tr>
          <th><%= @no+x+1 %></th>
          <td class="client-image"><%= image_tag client.try(:logo).try(:url, :thumb) %></td>
          <td><%= client.name %></td>
          <td>
            <%= link_to "Edit", edit_admin_client_path(client.id), :class => "btn btn-success" %>
            <%= link_to "Delete", admin_client_path(client.id ), :method => :delete,
                                  :data => {:confirm => "Are you sure?"}, :class => "btn btn-warning" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="col-xs-12 no_padding_lr pagination"><%= paginate @clients %></div>
</div>

tritunggal/app/views/admin/clients/new.html.erb
<div class="page-header">
  <div class="container">
    <div class="col-xs-12 col-sm-4 name no-padding-lr">New Client</div>
    <div class="col-xs-12 col-sm-8 breadcrumb">
      <ol class="breadcrumb">
        <li><%= link_to "Admin", admin_path %></li>
        <li><%= link_to "Clients", admin_clients_path %></li>
        <li class="active">New Client</li>
      </ol>
    </div>
  </div>
</div>

<div class="container">
  <%= render :partial => "shared/flash" %>
  <%= form_for([:admin, @client], :html => { :multipart => true,  :class => "form-horizontal"}) do |f| %>
    <%= render :partial => 'form', :locals => { :f => f} %>
    <div class="form-group">
      <div class="col-sm-2">&nbsp;</div>
      <div class="col-sm-10">
        <%= f.submit :class => "btn btn-success" %>
        <%= link_to 'Back', admin_clients_path, :class => "btn btn-info" %>
      </div>
    </div>
  <% end %>
</div>