tritunggal/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  resources :about_us, :only => [:index]
  resources :certificates, :only => [:index]
  resources :contact_us, :only => [:index, :create]
  get "/news" => "news#index", :as => "news"
  get "/news/:permalink" => "news#show", :as => "news_detail"
  get "products/search" => "products#search", :as => "product_search"
  get "products/:cat_permalink" => "products#index", :as => "products"
  get "products/:cat_permalink/:prod_permalink" => "products#show", :as => "product_detail"

  get "admin" => "admin/dashboard#index", :as => "admin"
  namespace :admin do
    resources :banners
    resources :categories
    resources :certificate_categories
    resources :certificates
    resources :clients
    resources :news
    get "product/products_by_category/:cat_permalink" => "products#products_by_category",
        :as => "products_by_category"
    get "contact_us_list" => "contact_us#index", :as => "contact_us_list"
    get "contact_us/:id" => "contact_us#show", :as => "contact_us"
    delete "contact_us/:id" => "contact_us#destroy", :as => "delete_contact_us"
    resources :products do
      member do
        resources :product_images, :param => :product_image_id
        resources :product_specifications, :param => :product_specification_id
      end
    end
    resources :system_settings, :only => [:edit, :update]
  end

  root 'home#index'

end

tritunggal/app/models/banner.rb
class Banner < ActiveRecord::Base
  mount_uploader :image, BannerUploader
end

tritunggal/app/controllers/admin/banners_controller.rb
class Admin::BannersController < Admin::ApplicationController
  before_filter :find_banner, :only => [:edit, :update, :destroy, :delete]

  def index
    @banners = Banner.order("#{sort_column} #{sort_direction}").page(params[:page]).per(20)
    @no = paging(20)
  end

  def new
    @banner = Banner.new
  end

  def create
    @banner = Banner.new(banner_params)
    if @banner.save
      flash[:notice] = 'Banner was successfully create.'
      redirect_to admin_banners_path
    else
      flash[:error] = "Banner failed to create"
      render :action => :new
    end
  end

  def edit
  end

  def update
    if @banner.update_attributes(banner_params)
      flash[:notice] = 'Banner was successfully updated.'
      redirect_to admin_banners_path
    else
      flash[:error] = "Banner failed to update"
      render :action => :edit
    end
  end

  def destroy
    flash[:notice] =  @banner.destroy ? 'Banner was successfully deleted.' :
                                           'Banner was falied to delete.'
    redirect_to admin_banners_path
  end

  private

    def banner_params
      params.require(:banner).permit(:image)
    end

    def find_banner
      @banner = Banner.find_by_id(params[:id])
      if @banner.nil?
        flash[:notice] = "Cannot find the Banner with id '#{params[:id]}'"
        redirect_to admin_banners_path
      end
    end

    def sort_column
      params[:sort] || "created_at"
    end

    def sort_direction
      params[:direction] || "desc"
    end
end

tritunggal/app/helpers/admin/banners_helper.rb
module Admin::BannersHelper
end

tritunggal/app/views/admin/banners/_form.html.erb
<% if @banner.errors.any? %>
  <div class="alert alert-danger alert-dismissable" group="alert">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
    </button>
    <h4><%= pluralize(@banner.errors.count, "error") %> prohibited this group from being saved:</h4>
    <ul>
    <% @banner.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= f.label :image, "Image", :class => "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.file_field :image, :class => "form-control" %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-2">&nbsp;</div>
  <div class="col-sm-10">
    Please upload image with size 800x1920 pixel (height x width)
  </div>
</div>

tritunggal/app/views/admin/banners/edit.html.erb
<div class="page-header">
  <div class="container">
    <div class="col-xs-12 col-sm-4 name no-padding-lr">Edit Banner</div>
    <div class="col-xs-12 col-sm-8 breadcrumb">
      <ol class="breadcrumb">
        <li><%= link_to "Admin", admin_path %></li>
        <li><%= link_to "Banners", admin_banners_path %></li>
        <li class="active">Edit Banner</li>
      </ol>
    </div>
  </div>
</div>

<div class="container">
  <%= render :partial => "shared/flash" %>
  <%= form_for([:admin, @banner], :html => { :multipart => true, :class => "form-horizontal"}) do |f| %>
    <div class="form-group">
      <div class="col-sm-12">
        <%= image_tag @banner.image.url(:medium) %>
      </div>
    </div>
    <%= render :partial => 'form', :locals => { :f => f} %>
    <div class="form-group">
      <div class="col-sm-2">&nbsp;</div>
      <div class="col-sm-10">
        <%= f.submit :class => "btn btn-success" %>
        <%= link_to 'Back', admin_banners_path, :class => "btn btn-info" %>
      </div>
    </div>
  <% end %>
</div>

tritunggal/app/views/admin/banners/index.html.erb
<div class="page-header">
  <div class="container">
    <div class="col-xs-12 col-sm-4 name no-padding-lr">Banners</div>
    <div class="col-xs-12 col-sm-8 breadcrumb">
      <ol class="breadcrumb">
        <li><%= link_to "Admin", admin_path %></li>
        <li class="active">Banners</li>
      </ol>
    </div>
  </div>
</div>

<div class="container">
  <%= render :partial => "shared/flash" %>
  <p><%= link_to "Add new banner", new_admin_banner_path %></p>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Image</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @banners.each_with_index do |banner, x| %>
        <tr>
          <th><%= @no+x+1 %></th>
          <td><%= image_tag banner.try(:image).try(:url, :thumb) %></td>
          <td>
            <%= link_to "Edit", edit_admin_banner_path(banner.id), :class => "btn btn-success" %>
            <%= link_to "Delete", admin_banner_path(banner.id ), :method => :delete,
                                  :data => {:confirm => "Are you sure?"}, :class => "btn btn-warning" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="col-xs-12 no_padding_lr pagination"><%= paginate @banners %></div>
</div>

tritunggal/app/views/admin/banners/new.html.erb
<div class="page-header">
  <div class="container">
    <div class="col-xs-12 col-sm-4 name no-padding-lr">New Banner</div>
    <div class="col-xs-12 col-sm-8 breadcrumb">
      <ol class="breadcrumb">
        <li><%= link_to "Admin", admin_path %></li>
        <li><%= link_to "Banners", admin_banners_path %></li>
        <li class="active">New Banner</li>
      </ol>
    </div>
  </div>
</div>

<div class="container">
  <%= render :partial => "shared/flash" %>
  <%= form_for([:admin, @banner], :html => { :multipart => true,  :class => "form-horizontal"}) do |f| %>
    <%= render :partial => 'form', :locals => { :f => f} %>
    <div class="form-group">
      <div class="col-sm-2">&nbsp;</div>
      <div class="col-sm-10">
        <%= f.submit :class => "btn btn-success" %>
        <%= link_to 'Back', admin_banners_path, :class => "btn btn-info" %>
      </div>
    </div>
  <% end %>
</div>