tritunggal/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  resources :about_us, :only => [:index]
  resources :certificates, :only => [:index]
  resources :contact_us, :only => [:index, :create]
  get "/news" => "news#index", :as => "news"
  get "/news/:permalink" => "news#show", :as => "news_detail"
  get "products/search" => "products#search", :as => "product_search"
  get "products/:cat_permalink" => "products#index", :as => "products"
  get "products/:cat_permalink/:prod_permalink" => "products#show", :as => "product_detail"

  get "admin" => "admin/dashboard#index", :as => "admin"
  namespace :admin do
    resources :banners
    resources :categories
    resources :certificate_categories
    resources :certificates
    resources :clients
    resources :news
    get "product/products_by_category/:cat_permalink" => "products#products_by_category",
        :as => "products_by_category"
    get "contact_us_list" => "contact_us#index", :as => "contact_us_list"
    get "contact_us/:id" => "contact_us#show", :as => "contact_us"
    delete "contact_us/:id" => "contact_us#destroy", :as => "delete_contact_us"
    resources :products do
      member do
        resources :product_images, :param => :product_image_id
        resources :product_specifications, :param => :product_specification_id
      end
    end
    resources :system_settings, :only => [:edit, :update]
  end

  root 'home#index'

end

tritunggal/app/models/product.rb
class Product < ActiveRecord::Base
  has_permalink :name, :update => true

  has_many :categories, :through => :categories_products, :dependent => :destroy
  has_many :categories_products, :dependent => :destroy
  has_many :certificates, :through => :certificates_products, :dependent => :destroy
  has_many :certificates_products, :dependent => :destroy
  has_many :product_images, :dependent => :destroy
  has_many :product_specifications, :dependent => :destroy

  accepts_nested_attributes_for :product_images, :product_specifications

  scope :best_seller, -> {where("best_seller = true")}

  def display_image
    self.product_images.first
  end

  def category
    self.categories.first
  end

end

tritunggal/app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::ApplicationController
  before_filter :find_product, :only => [:edit, :update, :destroy, :delete]
  before_filter :validate_categories, :only => [:create, :update]
  before_filter :validate_certificates, :only => [:create, :update]

  def index
    @products = Product.order("#{sort_column} #{sort_direction}").page(params[:page]).per(20)
    @no = paging(20)
  end

  def new
    @product = Product.new
    @product.short_specification = "
     <p></p><table class='table table-striped' style='width:100%'>
        <tr><td>title</td><td>:</td><td>info</td></tr>
        <tr><td></td><td>:</td><td></td></tr>
        <tr><td></td><td>:</td><td></td></tr>
        <tr><td></td><td>:</td><td></td></tr>
      </table><p></p>"
    @p_categories = Category.parent_categories.includes([:child_categories])
    @product_image = @product.product_images.build
    @product_categories = []
    certificate_cat = CertificateCategory.all
    @option_for_certificate = []
    certificate_cat.each do |cat|
      certicates_temp = []
      cat.certificates.each do |certificate|
        certicates_temp << [certificate.name, certificate.id]
      end
      @option_for_certificate << [cat.name] + [certicates_temp]
    end
  end

  def create
    @product = Product.new(product_params)
    @product.categories = @categories
    @product.certificates = @certificates
    @image_nil = params[:product_images].nil? ? true : false
    if !@image_nil && @product.save
      params[:product_images]['image'].each do |a|
        @product_image = @product.product_images.create!(:image => a)
      end
      unless params[:product_specifications].nil?
        params[:product_specifications]['filename'].each do |a|
          @product_specifications = @product.product_specifications.create!(:filename => a)
        end
      end
      flash[:notice] = 'Product was successfully create.'
      redirect_to admin_products_path
    else
      @p_categories = Category.parent_categories.includes([:child_categories])
      @product_categories = @product.categories.map(&:id)
      certificate_cat = CertificateCategory.all
      @option_for_certificate = []
      certificate_cat.each do |cat|
        certicates_temp = []
        cat.certificates.each do |certificate|
          certicates_temp << [certificate.name, certificate.id]
        end
        @option_for_certificate << [cat.name] + [certicates_temp]
      end
      params[:certificates] = @product.certificates.map(&:id)
      flash[:error] = "Product failed to create"
      flash[:error] += "<br />Image can't be blank!" if @image_nil
      render :action => :new
    end
  end

  def edit
    @p_categories = Category.parent_categories.includes([:child_categories])
    @product_categories = @product.categories.map(&:id)
    certificate_cat = CertificateCategory.all
    @option_for_certificate = []
    certificate_cat.each do |cat|
      certicates_temp = []
      cat.certificates.each do |certificate|
        certicates_temp << [certificate.name, certificate.id]
      end
      @option_for_certificate << [cat.name] + [certicates_temp]
    end
    params[:certificates] = @product.certificates.map(&:id)
  end

  def update
    if @product.update_attributes(product_params)
      @product.categories = @categories
      @product.certificates = @certificates
      @product.save
      flash[:notice] = 'Product was successfully updated.'
      redirect_to admin_products_path
    else
      @p_categories = Category.parent_categories.includes([:child_categories])
      flash[:error] = "Product failed to update"
      render :action => :edit
    end
  end

  def destroy
    flash[:notice] =  @product.destroy ? 'Product was successfully deleted.' :
                                           'Product was falied to delete.'
    redirect_to admin_products_path
  end

  def products_by_category
    @category = Category.find_by_permalink(params[:cat_permalink])
    if @category.nil?
      flash[:notice] = "Cannot find the Product with category '#{params[:cat_permalink]}'"
      redirect_to admin_products_path
    end
    @products = @category.products.order("#{sort_column} #{sort_direction}").page(params[:page]).per(20)
    @no = paging(20)
  end

  private

    def product_params
      params.require(:product).permit(:name, :sku, :short_specification, :specification,
                                      :certificate, :best_seller,
                                      :product_images_attributes =>[:id, :image, :product_id],
                                      :product_specifications => [:id, :filename, :product_id] )
    end

    def find_product
      @product = Product.find_by_id(params[:id])
      if @product.nil?
        flash[:notice] = "Cannot find the Product with id '#{params[:id]}'"
        redirect_to admin_products_path
      end
    end

    def validate_categories
      @categories=[]
      unless params[:category_ids].nil?
        @categories = Category.where("id in (?)", params[:category_ids])
      end
    end

    def validate_certificates
      @certificates = []
      unless params[:certificates].nil?
        @certificates = Certificate.where("id in (?)", params[:certificates])
      end
    end

    def sort_column
      params[:sort] || "created_at"
    end

    def sort_direction
      params[:direction] || "desc"
    end
end

tritunggal/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :find_category, :only => [:index, :show]
  before_filter :find_product, :only => [:show]

  def index
    order_by = params[:order_by].nil? ? "name" : params[:order_by]
    @products = @category.products.order(order_by).includes([:product_images]).page(params[:page]).per(12)
  end

  def show
    @product_images = @product.product_images
    @product_specifications = @product.product_specifications.group_by{|h| h.file_type}
    @certificates = @product.certificates
    @related_products = @category.products.sample(4)
  end

  def search
    @products = Product.where("name like '%#{params[:keyword]}%' OR sku like '%#{params[:keyword]}%'").
                       includes([:product_images]).page(params[:page]).per(12)
  end

  private
    def find_product
      @product = @category.products.find_by_permalink(params[:prod_permalink])
      if @product.nil?
        flash[:error] = "Cannot find product with name '#{params[:prod_permalink]}'"
        redirect_to products_path(@category.permalink)
      end
    end

    def find_category
      @category = Category.find_by_permalink(params[:cat_permalink])
      if @category.nil?
        flash[:error] = "Cannot find category with name '#{params[:cat_permalink]}'"
        redirect_to root_path
      end
    end
end

tritunggal/app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

tritunggal/app/helpers/products_helper.rb
module ProductsHelper
end

tritunggal/app/views/admin/products/_form.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "/assets/ckeditor/ckeditor", "select2.full.js" %>
  <%= stylesheet_link_tag  "select2.css" %>
<% end %>

<% if @product.errors.any? %>
  <div class="alert alert-danger alert-dismissable" group="alert">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
    </button>
    <h4><%= pluralize(@product.errors.count, "error") %> prohibited this group from being saved:</h4>
    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="col-sm-8">
  <div class="form-group">
    <%= f.label :name, "Name *", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
      <%= hidden_field_tag "id", params[:id] %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :sku, "SKU *", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :sku, :class => "form-control" %>
    </div>
  </div>
  <%= f.fields_for :post_attachments do |p| %>
    <div class="form-group">
      <%= f.label :image, "Images *", :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <% if action_name == 'edit' || action_name == 'update' %>
          Click 
          <%= link_to "here", admin_product_images_path(@product), :class => "green-link" %>
          to manages Product Images
        <% else %>
          <%= p.file_field :image, :multiple => true, :name => "product_images[image][]" %>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :short_specification, "Short Spec *", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.cktext_area :short_specification, :class => "form-control",
                        :ckeditor => {:uiColor => "#f0e5d2", :toolbar => "Basic"}%>
    </div>
  </div>
  <%#*<div class="form-group">%>
    <%#= f.label :specification, "Specification *", :class => "col-sm-2 control-label no-padding-l" %>
    <%#*<div class="col-sm-10">%>
      <%#= f.cktext_area :specification, :class => "form-control",
                        :ckeditor => {:uiColor => "#f0e5d2", :toolbar => "Basic"}%>
    <%#*</div>%>
  <%#*</div>%>
  <div class="form-group">
    <%= label_tag "certificates[]", "Certificates",
                  :class => "col-sm-2 control-label no-padding-l" %>
    <div class="col-sm-10">
      <%= select_tag "certificates[]", grouped_options_for_select(@option_for_certificate, params[:certificates]),
                      :multiple => true,
                      :include_blank => true, :class => "form-control select2" %>
    </div>
  </div>


  <%= f.fields_for :certificate_attachments do |p| %>
    <div class="form-group">
      <%= f.label :filename, "Specification *", :class => "col-sm-2 control-label no-padding-l" %>
      <div class="col-sm-10">
        <% if action_name == 'edit' || action_name == 'update' %>
          Click
          <%= link_to "here", admin_product_specifications_path(@product), :class => "green-link" %>
          to manages Product Specifications
        <% else %>
          <%= p.file_field :filename, :multiple => true, :name => "product_specifications[filename][]" %>
        <% end %>
      </div>
    </div>
  <% end %>


  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <%= f.check_box :best_seller %>Best Seller
        </label>
      </div>
    </div>
  </div>
</div>
<div class="col-sm-4">
  <h4>List Category</h4>
  <ul class="list-categories active">
    <% @p_categories.each do |cat| %>
      <li class="cat-item">
        <% if cat.child_categories.blank? %>
          <div class="checkbox">
            <label>
              <%= check_box_tag "category_ids[]", cat.id, @product_categories.include?(cat.id) %>
              <%= cat.name %>
            </label>
          </div>
        <% else %>
          <%= cat.name %>
          <ul class="list-child-category">
          <% cat.child_categories.each do |child| %>
            <li>
              <% if child.child_categories.blank? %>
                <div class="checkbox">
                  <label>
                    <%= check_box_tag "category_ids[]", child.id,
                                      @product_categories.include?(child.id) %>
                    <%= child.name %>
                  </label>
                </div>
              <% else %>
                <%= child.name %>
                <ul class="list-child-category">
                <% child.child_categories.each do |gs_child| %>
                  <li>
                    <div class="checkbox">
                      <label>
                        <%= check_box_tag "category_ids[]", gs_child.id,
                                          @product_categories.include?(gs_child.id) %>
                        <%= gs_child.name %>
                      </label>
                    </div>
                  </li>
                <% end %>
              </ul>
              <% end %>
            </li>
          <% end %>
        </ul>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $(".select2").select2({
      tags: true
    });
  })
</script>

tritunggal/app/views/admin/products/edit.html.erb
<div class="page-header">
  <div class="container">
    <div class="col-xs-12 col-sm-4 name no-padding-lr">Edit Product</div>
    <div class="col-xs-12 col-sm-8 breadcrumb">
      <ol class="breadcrumb">
        <li><%= link_to "Admin", admin_path %></li>
        <li><%= link_to "Products", admin_products_path %></li>
        <li class="active">Edit Product</li>
      </ol>
    </div>
  </div>
</div>

<div class="container">
  <%= render :partial => "shared/flash" %>
  <%= form_for([:admin, @product], :html => { :multipart => true,  :class => "form-horizontal"}) do |f| %>
    <%= render :partial => 'form', :locals => { :f => f} %>
    <div class="form-group">
      <div class="col-sm-2">&nbsp;</div>
      <div class="col-sm-10">
        <%= f.submit :class => "btn btn-success" %>
        <%= link_to 'Back', admin_products_path, :class => "btn btn-info" %>
      </div>
    </div>
  <% end %>
</div>

tritunggal/app/views/admin/products/index.html.erb
<div class="page-header">
  <div class="container">
    <div class="col-xs-12 col-sm-4 name no-padding-lr">Products</div>
    <div class="col-xs-12 col-sm-8 breadcrumb">
      <ol class="breadcrumb">
        <li><%= link_to "Admin", admin_path %></li>
        <li class="active">Products</li>
      </ol>
    </div>
  </div>
</div>

<div class="container">
  <%= render :partial => "shared/flash" %>
  <p><%= link_to "Add new product", new_admin_product_path %></p>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Image</th>
        <th class="green-link"><%= sortable("name", "Name") %></th>
        <th class="green-link"><%= sortable("sku", "SKU") %></th>
        <th>Categories</th>
        <th>Certificates</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each_with_index do |product, x| %>
        <tr>
          <th><%= @no+x+1 %></th>
          <td><%= image_tag product.display_image.try(:image).try(:url, :thumb) %></td>
          <td><%= product.name %></td>
          <td><%= product.sku %></td>
          <td>
            <% product.categories.each do |cat| %>
              <%= link_to cat.name, admin_products_by_category_path(cat.permalink) %><br />
            <% end %>
          </td>
          <td>
            <% product.certificates.each do |certificate| %>
              <%= link_to certificate.name, edit_admin_certificate_path(certificate.id) %><br />
            <% end %>
          </td>
          <td>
            <%= link_to "Product Images", admin_product_images_path(product), :class => "btn btn-info" %>
            <%= link_to "Spec", admin_product_specifications_path(product), :class => "btn btn-danger" %>
            <%= link_to "Edit", edit_admin_product_path(product), :class => "btn btn-success" %>
            <%= link_to "Delete", admin_product_path(product.id ), :method => :delete,
                                  :data => {:confirm => "Are you sure?"}, :class => "btn btn-warning" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="col-xs-12 no_padding_lr pagination"><%= paginate @products %></div>
</div>

tritunggal/app/views/admin/products/new.html.erb
<div class="page-header">
  <div class="container">
    <div class="col-xs-12 col-sm-4 name no-padding-lr">New Product</div>
    <div class="col-xs-12 col-sm-8 breadcrumb">
      <ol class="breadcrumb">
        <li><%= link_to "Admin", admin_path %></li>
        <li><%= link_to "Products", admin_products_path %></li>
        <li class="active">New Product</li>
      </ol>
    </div>
  </div>
</div>

<div class="container">
  <%= render :partial => "shared/flash" %>
  <%= form_for([:admin, @product], :html => { :multipart => true,  :class => "form-horizontal"}) do |f| %>
    <%= render :partial => 'form', :locals => { :f => f} %>
    <div class="form-group">
      <div class="col-sm-2">&nbsp;</div>
      <div class="col-sm-10">
        <%= f.submit :class => "btn btn-success" %>
        <%= link_to 'Back', admin_products_path, :class => "btn btn-info" %>
      </div>
    </div>
  <% end %>
</div>

tritunggal/app/views/admin/products/products_by_category.html.erb
<div class="page-header">
  <div class="container">
    <div class="col-xs-12 col-sm-7 name no-padding-lr"><%= @category.name.titleize %> Products</div>
    <div class="col-xs-12 col-sm-5 breadcrumb">
      <ol class="breadcrumb">
        <li><%= link_to "Admin", admin_path %></li>
        <li><%= link_to "Products", admin_products_path %></li>
        <li class="active"><%= @category.name.titleize %></li>
      </ol>
    </div>
  </div>
</div>

<div class="container">
  <%= render :partial => "shared/flash" %>
  <p><%= link_to "Add new product", new_admin_product_path %></p>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Image</th>
        <th class="green-link"><%= sortable("name", "Name") %></th>
        <th class="green-link"><%= sortable("sku", "SKU") %></th>
        <th>Categories</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each_with_index do |product, x| %>
        <tr>
          <th><%= @no+x+1 %></th>
          <td><%= image_tag product.display_image.try(:image).try(:url, :thumb) %></td>
          <td><%= product.name %></td>
          <td><%= product.sku %></td>
          <td>
            <% product.categories.each do |cat| %>
              <%= link_to cat.name, admin_products_by_category_path(cat.permalink) %><br />
            <% end %>
          </td>
          <td>
            <%= link_to "Product Images", admin_product_images_path(product), :class => "btn btn-info" %>
            <%= link_to "Edit", edit_admin_product_path(product), :class => "btn btn-success" %>
            <%= link_to "Delete", admin_product_path(product.id ), :method => :delete,
                                  :data => {:confirm => "Are you sure?"}, :class => "btn btn-warning" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="col-xs-12 no_padding_lr pagination"><%= paginate @products %></div>
</div>